### ISSUE TITLE
add FIDO2 support

### ISSUE THREAD

**Issue by elkimek** [turtlecoin/turtle-wallet-proton#62]
It would be nice to have FIDO2 support as a an auth. method with devices such as Yubikey, Trezor, etc.

As a bonus, TurtleCoin would have interoperability with Trezor, which is also supporting FIDO2 and would be great starting point to get TurtleCoin integrated in future as it is one of the unofficial requirements to get integrated in Trezor web wallet.

**Comment by ExtraHash** [comment]
I don't know much about this at all, but I'll look into it and see how the authentication procedure works.

**Comment by ExtraHash** [comment]
I don't think this is really possible from my research into how the authentication procedure works: it seems like it's mostly designed for web apps that handle login credentials on a centralized server. Since our wallet is just a locally encrypted file, I don't think it's very applicable for our use case. I'm going to close this for now.
