### ISSUE TITLE
add the ability to export / import & broadcast offline transactions

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtle-wallet-proton#64]
not sure if this is in the js backend or not yet but this is a must-have tool imo

**Comment by zpalmtree** [comment]
This is not currently in the backend. Allowing creation of a transaction and subsequent submitting would work, but would potentially run into issues with the relevant inputs having been spent meanwhile. I don't want to store that as part of the wallet data to manage that, like walletgreen does.

One stumbling block is that if you want to create a transaction offline, you will need to get ring participants (getRandomOutsByAmount) to mix the transaction with.

**Comment by ExtraHash** [comment]
i'm thinking this would be used by people for spending from cold wallets without exposing their keys to an online machine, would it not make sense to simply manually remove the spent inputs if a manual transaction was created?

**Comment by zpalmtree** [comment]
We could do that, yes, but there's no way to recover from the user then not spending the transaction, unless they rescan. On the other hand, if they spend inputs that have not been removed from the wallet, that will automatically be resolved by the wallet upon scanning that block.

**Comment by SoreGums** [comment]
The cold wallet offline-signing thing is usually done by have a "view/maker" wallet online and the "private key signing" offline. As long as the view wallet can gather the material required to pre-stage the transaction for the hashing/signing process, it'll work fine.

Can avoid the issue of wallet out of sync as the view wallet is online and looking through transactions and keeping track of things. As a first step the view wallet could be done in a way that only a single "signed elsewhere" transaction can exist. Since there are no private keys to actually spend anything, it is blocked. The second step would then be to do it so it can have multiple queued transactions provided there are enough unspent outputs available to assemble the required amount for the new transaction.

Could probably come up with a sensibly structured blob of some kind (json, bencoded dictionary, other) and stick it in a QR code (if the signing device was a laptop with a webcam or a phone) else a regular file on a USB works fine.

All the signing device does is read in the blob and do the hashing to create a TX, the external parts of random inputs has already been done by the "view/maker" wallet. either shows a qr of the raw tx ready to send to any daemon or produces a file that goes back on the USB to be sent from any wallet that understands to any daemon.

The obvious flaw in this is the selection process for the inputs to be mixed with. As things happen between generating the unhashed tx and the hashed tx being sent, the mixed inputs might not be of the best obscurity. They could have been used in other tx in the meantime. Without analysing all of that part of it and understanding the impact here, the privacy parts are not as strong as they are for online hashed tx, something to consider if this kind of function is OK or not. Maybe if it were time-restricted it would reduce the issues, think ledger/other hw wallet signing immediately.

**Comment by ExtraHash** [comment]
I don't believe that's true at all, an offline transaction is typically signed by the "private key signing" wallet offline and then the raw signed transaction is broadcasted somehow to a node. A view only wallet is not necessary for the process.

**Comment by SoreGums** [comment]
how does that work?

if there is no part of the wallet online - how does it gather up the required unspent outputs to feed as inputs to the new transaction?

Even in bitcoin there is a view only wallet. am I missing something?

**Comment by brandonlehmann** [comment]
You need to be “online” to get random outputs to mix with unless you get crafty.

**Comment by SoreGums** [comment]
There is another version of "cold storage" in bitcoin. it is the paper wallet is never used for transactions. it is purely offline and when wanting to move any of the coins later, all of them are moved to an online wallet.

I was going after the cold wallet that does any number of transactions version.

> You need to be “online” to get random outputs to mix with unless you get crafty.
This is how the [Electrum guides](http://docs.electrum.org/en/latest/coldstorage.html) work for what I described. offline part and online part, 2 different devices. The online part is in "watch only" mode - since over here in CryptoNote it is called a View key, I called it a "view" wallet :)

**Comment by brandonlehmann** [comment]
Not disagreeing with you @soregums :) it’s not impossible to operate 100% offline. Just takes a bit of online work.

**Comment by ExtraHash** [comment]
on non-private chains like bitcoin or eth, you can dump the signed transaction to hex and broadcast them to the network with something like this 

https://live.blockcypher.com/btc/pushtx/

https://etherscan.io/pushTx

I can understand that the mixing requirement definitely makes this a bit more difficult to do, but this is the kind of experience i'm looking for out of this.

**Comment by brandonlehmann** [comment]
We already have that. Please review TurtleCoin-utils which creates the raw transaction and then uses the node /sendrawtransaction method

**Comment by SoreGums** [comment]
> you can dump the signed transaction to hex

yeah - I am saying that as well - however, it seems like you're discounting the "gather the required data" to actually generate said "signed transaction". Everything I wrote was about:
 - gathering that data
 - having the wallet that gathered that info be capable of continuing to gather info for more transactions and keep an accurate balance
 - handle the situation where "signed transaction" was never broadcast
 - handle the situation where the person has multiple offline/cold setups and does things in a non-sequential way

**Comment by ExtraHash** [comment]
> We already have that. Please review TurtleCoin-utils which creates the raw transaction and then uses the node /sendrawtransaction method

*looks around*
which repo do you think you're on?

**Comment by SoreGums** [comment]
so i fired with a false assumption - have edited my op.

**Comment by brandonlehmann** [comment]
> > We already have that. Please review TurtleCoin-utils which creates the raw transaction and then uses the node /sendrawtransaction method
> 
> _looks around_
> which repo do you think you're on?

You're using the backend, which uses turtlecoin-utils for the transaction creation. Perhaps you're like to review your dependency chain.

**Comment by ExtraHash** [comment]
> > > We already have that. Please review TurtleCoin-utils which creates the raw transaction and then uses the node /sendrawtransaction method
> > 
> > 
> > _looks around_
> > which repo do you think you're on?
> 
> You're using the backend, which uses turtlecoin-utils for the transaction creation. Perhaps you'd like to review your dependency chain.

the fact remains that this is an issue about implementing a feature into the client itself, not a feature into turtlecoin in general****

**Comment by brandonlehmann** [comment]
> > > > We already have that. Please review TurtleCoin-utils which creates the raw transaction and then uses the node /sendrawtransaction method
> > > 
> > > 
> > > _looks around_
> > > which repo do you think you're on?
> > 
> > 
> > You're using the backend, which uses turtlecoin-utils for the transaction creation. Perhaps you'd like to review your dependency chain.
> 
> the fact remains that this is an issue about implementing a feature into the client itself, not a feature into turtlecoin in general

very well. GLHF

**Comment by ExtraHash** [comment]
closing as this is no longer really a priority for me
