### ISSUE TITLE
wallet does not properly detect saving in program directory if wallet is added to a subdirectory

### ISSUE THREAD

**Issue by gthreadgill** [turtlecoin/turtle-wallet-proton#98]
When the new install of the Proton wallet is applied it goes in and erases the old wallet completely. Be mindful to make another copy of the old wallet somewhere else before doing this install. The other important workaround for this is to make sure you have a copy of your keys or a backup file for your wallet. Do not forget this step. This is for the Turtlecoin crypto. Proton-Wallet Setup 1.0.0. exe file

**Comment by ExtraHash** [comment]
The waller is not erased, it simply doesn't have the required file extension for the picker to see it. just add .wallet to your wallet file and your old wallet file

**Comment by ExtraHash** [comment]
This is detailed in the release notes for 1.0.0 here:

https://github.com/turtlecoin/turtle-wallet-proton/releases/tag/v1.0.0

**Comment by gthreadgill** [comment]
This part of what you shared I am aware of that but when I installed the
new setup file it wrote over everything I had previously installed from the
previous version. It erased the folder that I had the wallet in and the
wallet file. This folder was inside of the proton-wallet folder. So when I
went to do what you instructed me to do with adding the .wallet extension
this is when I discovered that the folder I created with the wallet file
was deleted in the update installation to version 1.0.0

**Comment by ExtraHash** [comment]
The installer does not wipe any folders besides the program directory, which it restricts you from saving in. What operating system are you on and where was the location of your wallet?

**Comment by gthreadgill** [comment]
Windows 10 and my wallet was in my program directory folder for
proton-wallet in a sub folder Labeled “Storage”

**Comment by ExtraHash** [comment]
Just to confirm, you mean the C:/Program Files/proton-wallet directory or similar?

If so, the wallet shouldn't have let you save there because of this: I think I only checked if you're *in* the exact path though, so putting it in a subdirectory probably bypassed that. I'll have to update that check to see if it contains the path instead of matches exactly.

**Comment by gthreadgill** [comment]
I installed my wallets to an external drive. This was in
J:/wallets/Turtles/Proton-wallet. My wallet was in a sub folder called
Storage. That way the blockchain when downloaded do not take up space on my
system hard drive. Depending on the wallet.

**Comment by gthreadgill** [comment]
The install allows you to choose where you want the installation to be
placed. Plus where to put the wallet

**Comment by ExtraHash** [comment]
The installer doesn't ask anything about where to put the wallet file, merely where to install the program. Also, the "new wallet" save dialog opens by default in my documents. 

If you would have tried to save your wallet directly in J:/wallets/Turtles/Proton-wallet, the wallet would have told you not to do this as the installer wipes the program directory on update, but since you put it in a subdirectory it bypassed this check.

I will update this check to fix this scenario, but bottom line is you can't save your wallet in the same folder that the program is installed in.

**Comment by gthreadgill** [comment]
The reason I did that is because most of the wallets I have the wallet file
is within the wallet program folder and when and update is done the wallet
file is not bothered if it is present. The program updates the files and
folders included and leaves all other created folders alone. If I had been
prompted that it would erase everything then I would have made an extra
copy of my wallet folder and file.

**Comment by gthreadgill** [comment]
Lesson once again learned 16000 turtle coins later. Just trying to help the
next person not to make the same mistake.

**Comment by ExtraHash** [comment]
I apologize about that, if I hadn't made an error in my logic for checking the save directory it would have saved you some heartache. Thanks for bringing this to my attention though, as I said, I will update this check to ensure even if a subdirectory is created it restricts you from saving there.

**Comment by ExtraHash** [comment]
I have fixed the check in f395b8b2

The wallet will now not allow you to save in any child directory of the program directory. Thanks for the report
